### ISSUE TITLE
How to install torchvision

### ISSUE THREAD

**Issue by andrehuang** [peterjc123/pytorch-scripts#4]
I was trying to install torchvision on Windows10 using Anaconda, after installing torch from this repository but failed. The output is this. What is the problem?

`>pip install pytorch`

```
Collecting pytorch
  Downloading pytorch-0.1.2.tar.gz
Building wheels for collected packages: pytorch
  Running setup.py bdist_wheel for pytorch ... error
  Complete output from command "C:\Program Files\Anaconda3\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\ANDREH~1\\AppData\\Local\\Temp\\pip-build-6x9x6_wq\\pytorch\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\ANDREH~1\AppData\Local\Temp\tmpp5codq2dpip-wheel- --python-tag cp36:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\ANDREH~1\AppData\Local\Temp\pip-build-6x9x6_wq\pytorch\setup.py", line 17, in <module>
      raise Exception(message)
  Exception: You should install pytorch from http://pytorch.org
```

  ----------------------------------------
 ```
 Failed building wheel for pytorch
  Running setup.py clean for pytorch
Failed to build pytorch
Installing collected packages: pytorch
  Running setup.py install for pytorch ... error
    Complete output from command "C:\Program Files\Anaconda3\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\ANDREH~1\\AppData\\Local\\Temp\\pip-build-6x9x6_wq\\pytorch\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ANDREH~1\AppData\Local\Temp\pip-_2gv8q3_-record\install-record.txt --single-version-externally-managed --compile:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ANDREH~1\AppData\Local\Temp\pip-build-6x9x6_wq\pytorch\setup.py", line 13, in <module>
        raise Exception(message)
    Exception: You should install pytorch from http://pytorch.org
```

    ----------------------------------------
`Command ""C:\Program Files\Anaconda3\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\ANDREH~1\\AppData\\Local\\Temp\\pip-build-6x9x6_wq\\pytorch\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ANDREH~1\AppData\Local\Temp\pip-_2gv8q3_-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ANDREH~1\AppData\Local\Temp\pip-build-6x9x6_wq\pytorch\`

**Comment by peterjc123** [comment]
Why don't you read the README before install pyTorch?
For installing torchvision, you'll just have to do the following.
```CMD
pip install torchvision
```
