### ISSUE TITLE
iter出错

### ISSUE THREAD

**Issue by BroadDong** [peterjc123/pytorch-scripts#9]
dataiter = iter(trainloader)，运行到此处时，会报错，如下（请指导一下原因，非常感谢）
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Broad\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Broad\Anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\Broad\Anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Broad\Anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\Broad\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Broad\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Broad\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\测试程序\PyCharmTest\CIFAR_10_Classify.py", line 87, in <module>
    dataiter = iter(trainloader)
  File "C:\Users\Broad\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 310, in __iter__
    return DataLoaderIter(self)
  File "C:\Users\Broad\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 167, in __init__
    w.start()
  File "C:\Users\Broad\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Broad\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Broad\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Broad\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Broad\Anaconda3\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Broad\Anaconda3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "E:/测试程序/PyCharmTest/CIFAR_10_Classify.py", line 87, in <module>
    dataiter = iter(trainloader)
  File "C:\Users\Broad\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 310, in __iter__
    return DataLoaderIter(self)
  File "C:\Users\Broad\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 167, in __init__
    w.start()
  File "C:\Users\Broad\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Broad\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Broad\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Broad\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Broad\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by peterjc123** [comment]
程序入口请使用如下if判断来包裹：
```
if __name__ == '__main__':
    # do something here
```
如果还不行，请尝试将num_worker设置为0.

**Comment by BroadDong** [comment]
好的，非常感谢
